// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArEIqR3BfOzAiRK7usYNTonCKBHDLnvLg',
    appId: '1:756932422382:web:efb1170b24e46c034121ff',
    messagingSenderId: '756932422382',
    projectId: 'dreambus-project',
    authDomain: 'dreambus-project.firebaseapp.com',
    storageBucket: 'dreambus-project.appspot.com',
    measurementId: 'G-57ZYHGYPND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0S7zxT4bgwNa2t66cmSOotVjHiiCLewA',
    appId: '1:756932422382:android:e50113a9c947bad84121ff',
    messagingSenderId: '756932422382',
    projectId: 'dreambus-project',
    storageBucket: 'dreambus-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK8IPdnsf_Et848l8X65uk1rmLkppBLO4',
    appId: '1:756932422382:ios:37ad8b9fadc14d9a4121ff',
    messagingSenderId: '756932422382',
    projectId: 'dreambus-project',
    storageBucket: 'dreambus-project.appspot.com',
    iosBundleId: 'com.example.happyBusDriver',
  );
}
