name: PushToTesters 

/// These are the events which will trigger the automation process/
on: [pull_request, push] 
    
   
    branches:
      - main

jobs: 

 
  build_and_deploy: 
    
    
    runs-on: ubuntu-latest 

    /// Setup the platform and the required dependencies
    /// Example - Java and Flutter
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

     
      - name: Build Gradle
        run: flutter build apk --release
      - run: ls build/app/outputs/flutter-apk

      
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          
          appId: ${{secrets.APP_ID}} 

          /// We'll be setting these up later in the tutorial.
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}

          /// This is the name of the group of tester, 
          /// to whom the apk will be distributed.
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk